- README.md
- kiteconnect/__init__.py
- setup.py
Added option to disable ssl cert verification.
```
from kiteconnect import WebSocket
kws = WebSocket("your_api_key", "your_public_token", "logged_in_user_id")
kws.connect(disable_ssl_verification=True)
```
> Option to disable ssl cert verification

- kiteconnect/__init__.py
Fixes minor typo (`s/secret/api_secret`) present in the [docs](https://github.com/zerodhatech/pykiteconnect/blob/kite3/kiteconnect/__init__.py#L41)
> kiteconnect/__init__.py: Fix typo in positional argumnet

- kiteconnect/ticker.py
datetime.fromtimestamp uses time.localtime behind the scenes. Python
time module is a c extension which depends on os.
Behaviour:
Invalid datetime epoch raise oserror on windows but raises valueerror
on macos/linux flavours
> fix: Datetime module raises oserror on windows

- dev_requirements.txt
- kiteconnect/ticker.py
This is an ugly hack to prevent resubscription if there was an unclean closure before. What if the connection is a new one / server removes the connection?
> fix: Do not subscribe if there was an unclean closure before

- kiteconnect/ticker.py
This reverts commit c719c8492f9cdbb4680d3f1dfa8270b0dc2001c4.
@vividvilla 
This commit was added under the assumption that on abnormal closure, websocket client uses the same tcp connection. Ticker server has max tokens per connection. In case of abnormal closure and if the client uses the same connection to reconnect, the server will throw max tokens exceeded error. Looks like that is not the case [always](https://kite.trade/forum/discussion/6841/not-receiving-new-ticks-after-re-connection#latest). Reverting this hacky commit and changing on the server.
> Revert "fix: Do not subscribe if there was an unclean closure before"

- setup.py
* https://github.com/pypa/pip/issues/6998
Do not assume egg install for all setuptools version
> fix: Use setuptools egg install runner

- docs/index.html
The href url of an a tag in the documentation was not redirecting to the correct url, but was redirecting relatively which has been fixed.
> fix: corrected kite.trade url in documentation

- kiteconnect/connect.py
Params argument assignment was missed. Because of which **_put** method was not considering the payload, resulting in 400.
> Fix:param arg in convert_position method

- examples/simple.py
The order placement example had the wrong product type for NSE-EQ.
> Fix: Place order product type param

- examples/flask_app.py
kite connect login url `https://api.kite.trade/connect/login?api_key={api_key}`, cannot be used anymore and updated with latest url `https://kite.trade/connect/login?api_key={api_key}`
> updating kite trade api url for login

- README.md
`variety` seems to be a mandatory parameter but it isn't used in the "Getting Started" example in the `README.md`
> Adds required variety parameter in place_order

- kiteconnect/connect.py
Request:
`curl "https://api.kite.trade/mf/orders" -H "X-Kite-Version: 3" -H "Authorization: token <api_key>:<access_token>" -d "tradingsymbol=INF174K01LSS" -d "transaction_type=BUY" -d "amount=1000"`
Response:
```{"status":"error","message":"Invalid `isin`","data":{}}```
I think it would be great if there were an error_type with this response so that an exception is raised in case of an invalid payload with some information with what went wrong. I also noticed similar behaviour with `/mf/sips` and a few other apis. This should hopefully help work around that.
> raise exception for status=error but no error_type in response

- examples/gtt_order.py
- kiteconnect/ticker.py
1. Add single leg and OCO(two-leg) GTT order example.
2. Update ticker structure sample response in the[ documentation](https://kite.trade/docs/pykiteconnect/v4/#kiteconnect.KiteTicker).
> chores: add GTT order examples

- .github/workflows/test-conda.yml
- .github/workflows/test.yml
- dev_requirements.txt
Include the latest python versions 3.9 and 3.10 to the workflow.
> feat: add py version 3.9 and 3.10 to tests

- setup.py
Remove enum34 deps as it is no more required.
> feat: remove enum34 deps from install require

- kiteconnect/__init__.py
`[text](link)`, not `[link](text)`. Gets us all the time.
> fix: link correctly to kite.trade

- kiteconnect/connect.py
Add deprecation warning message for all BO properties including constant `VARIETY_BO` and `PRODUCT_BO` and `place_order` input params `squareoff`, `stoploss` and `trailing_stoploss`. It will be removed in the next major release.
> feat: add deprecation warning for all BO properties

- kiteconnect/ticker.py
Initialize ws object in KiteTicker class, to avoid AttributeError for `is_connected` and `_close` method calls.
> fix: initialize ws object in KiteTicker class

- kiteconnect/ticker.py
Gracefully exit the websocket once maximum retry attempts is exhausted.
> fix: gracefully exit websocket for exceeding max retry attempts

- .github/workflows/test-conda.yml
- .github/workflows/test.yml
- kiteconnect/connect.py
- tests/unit/test_kite_object.py
This PR introduces below changes:
1. Create requests session object by default for connection reuse.
2. Fix unit tests related to the above changes.
3. Update gitlab CI file to use ubuntu-20.04 instead of ubuntu-latest because of [this workflow error](https://github.com/zerodha/pykiteconnect/actions/runs/3547545557/jobs/5957781913#step:4:7).
> feat: create session object by default

- dev_requirements.txt
- kiteconnect/ticker.py
- Remove [sendPing](https://github.com/crossbario/autobahn-python/blob/359f868f9db410586cf01c071220994d8d7f165a/autobahn/websocket/interfaces.py#L572) overide in websocket for ping.
- [Force install urllib3<2.0](https://github.com/psf/requests/issues/6432#issuecomment-1535149114) to support openSSL in workflow
> fix: downgrade urllib3 version to support openSSL in workflow
