zerodha/pykiteconnect

README.md, kiteconnect/__init__.py
Post #1 I noticed `kite.instruments()` wasn't working due to response being csv. 
Have suggested a fix for it as well as some documentation comments for easy parsing of csv response in python.
@knadh I am closing #1 , as this contains all those fixes as well.
=> All instruments csv fix

kiteconnect/__init__.py
=> Fix market depth binary parsing, buy coming as sell

kiteconnect/__init__.py, setup.py
Added six for Python 3.* Added six dependency as it more elegant than 
```
try:
from StringIO import StringIO
except ImportError:
from io import StringIO
```
=> Added six for Python 3.*

kiteconnect/__init__.py
=> Fix tick structure for market depth in docstring

.gitignore, README.md, kiteconnect/__init__.py, setup.cfg, setup.py
Auto reconenctions is not enabled by default and it can be enabled by setting `enable_reconnect` method. 
```
kws.enable_reconnect(reconnect_interval=5, reconnect_tries=50)
```
=> Auto reconnection feature

kiteconnect/__init__.py
Setting of handlers, log level should happen on the application end
=> Remove attaching streamhandler

kiteconnect/connect.py, tests/unit/test_exceptions.py
@vividvilla Please review and merge
=> Add tests for all exceptions

kiteconnect/ticker.py, setup.py, tests/unit/conftest.py, tests/unit/test_ticker.py
@vividvilla Can you please test websocket on python 3 env.
=> Add basic test for kite websocket protocol

examples/flask_app.py
@vividvilla 
Added serializer and removed deprecated holdings_url, orders_url from L83, L88 respectively
=> fix(examples): Add serializer

appveyor.yml, setup.cfg
=> test: Add appveyor for windows test builds

kiteconnect/connect.py, kiteconnect/ticker.py
=> fix: Create requests session only if pooling

tests/unit/conftest.py, tests/unit/test_kite_object.py
=> test: Add test for connection pooling

setup.py
@vividvilla Award token please :clinking_glasses:
=> fix: Fake dist-dir option on bdist_wheel

CHANGELOG.md, examples/order_margins.py
Add example for order margin and update changelog of addition about order margin API.
=> Add: example for order_margin and update ChangeLog

kiteconnect/connect.py
Added new constant of POSITION_TYPE_DAY and POSITION_TYPE_OVERNIGHT for position conversion.
=> feat: Add new constants for position type

kiteconnect/connect.py
Fix lint error for constant assignment.
=> Fix:lint error

tests/mock_responses/profile.json
Added `user_id` and `meta` fields to user profile mock response.
=> feat: update mock response for user profile

docs/index.html, kiteconnect/connect.py
Add `order_margins` in python client documentation. Create new docs using `pdoc --html --html-dir docs kiteconnect`.
=> feat: update new order_margins in docs

examples/order_margins.py, kiteconnect/connect.py
- Refactored _request method to receive URL query parameters along with JSON payload using query_param dict.
- Added basket order margin API.
- Add example for basket order margin API.
=> feat: add basket order margin

examples/flask_app.py, examples/order_margins.py, examples/threaded_ticker.py, examples/ticker.py, kiteconnect/ticker.py
=> fix: update ticker examples

README.md, kiteconnect/__init__.py
Update order placement example in [client doc](https://kite.trade/docs/pykiteconnect/v3/).
=> fix: update getting started example for order placement

kiteconnect/connect.py
=> fix: bcd exchange constant

kiteconnect/connect.py, kiteconnect/ticker.py
Add [iceberg and TTL orders](https://kite.trade/docs/connect/v3/orders/#glossary-of-constants).
=> feat: add iceberg and TTL orders

kiteconnect/connect.py
Replace json.loads with requests built-in JSON decoder.
=> chores: use requests builtin JSON decoder

examples/flask_app.py, kiteconnect/connect.py, tests/integration/test_connect_write.py
Remove depreciated bracket order input params from `place_order` and tests.
=> chore: remove depreciated bracket order params and tests
